### ISSUE TITLE
Referentie naar HalCollectionLinks werkt niet

### ISSUE THREAD

**Issue by fsamwel** [Geonovum/KP-API-guidelines#4]
Wanneer ik in de Open API specificatie het volgende specificeer bij een operatie:
```
          content:
            application/hal+json:
              schema:
               type: object
               properties:
                 _links:
                   $ref: 'https://cdn.jsdelivr.net/gh/geonovum/kp-api-guidelines@1.0.0/components/schemas.yaml#/HalCollectionLinks'
```

Krijg ik in Swaggerhub een voorbeeldbericht met '"_links": {},'. De inhoud van HalCollectionLinks komt dus niet goed mee. Foutje in de manier waarop ik het gebruik, foutje in Swaggerhub of foutje in schemas.yaml#/HalCollectionLinks?

**Comment by dvh** [comment]
Bij mij werkt het... `content` staat wel onder `/paths/collectie/get/responses/200`?

**Comment by fsamwel** [comment]
Ja. In mijn geval is de opbouw:
```
paths:
  /ingeschrevenpersonen:
    get:
      responses:
        '200':
          content:
            application/hal+json:
              schema:
               type: object
               properties:
                 _links:
                   $ref: 'https://cdn.jsdelivr.net/gh/geonovum/kp-api-guidelines@1.0.0/components/schemas.yaml#/HalCollectionLinks'
```

**Comment by fsamwel** [comment]
https://app.swaggerhub.com/apis/VNG-sandbox/bevragingen-ingeschreven_personen/1.0

**Comment by dvh** [comment]
Ik krijg daar keurig deze voorbeeld response:

```
{
  "_links": {
    "self": {
      "href": "string"
    },
    "next": {
      "href": "string"
    }
  },
  "_embedded": {
    "ingeschrevenpersonen": [
      {
         ...
```

Doet https://cdn.jsdelivr.net/gh/geonovum/kp-api-guidelines@1.0.0/components/schemas.yaml#/HalCollectionLinks het überhaupt wel daar?

**Comment by fsamwel** [comment]
Vreemd,  nu doet hij het wel. Probleem opgelost (of is nooit een probleem geweest)
